apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-devops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-devops
  template:
    metadata:
      labels:
        app: hello-devops
    spec:
      containers:
      - name: hello-devops-container
        image: sreerajsree/hello-devops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"